from setuptools import setup, find_packages
setup(name='gdrive',
      version='0.1.2',
      packages=find_packages(exclude=['docs', 'tests']),
      install_requires=['funcsigs>=0.4',
                        'google-api-python-client>=1.5.0',
                        'httplib2>=0.9.2',
                        'mock>=1.3.0',
                        'oauth2client>=2.0.0.post1',
                        'pbr>=1.8.1',
                        'py>=1.4.31',
                        'pyasn1>=0.1.9',
                        'pyasn1-modules>=0.0.8',
                        'PyDrive>=1.0.1',
                        'pytest>=2.8.7',
                        'PyYAML>=3.11',
                        'rsa>=3.3',
                        'simplejson>=3.8.2',
                        'six>=1.10.0',
                        'uritemplate>=0.6',
                        'urllib3>=1.14',
                        'wheel>=0.29.0',
                        ],
      author="Matthew Cox",
      author_email="matthew.cox@teachforamerica.org",
      )
